import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { ChatsSidebar } from "@/components/chats-sidebar";
import { SidebarProvider } from "@/components/ui/sidebar";
import { ReactQueryProvider } from "@/components/providers/react-query";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main>
          <ReactQueryProvider>
            <SidebarProvider>
              <ChatsSidebar />
              <div className="w-full">{children}</div>
            </SidebarProvider>
          </ReactQueryProvider>
        </main>
      </body>
    </html>
  );
}
